import React, { useEffect, useState, useMemo } from 'react';
import { suspectsApi } from '../api/index';
import { PageHeader } from '../components/common/PageHeader';
import { SuspectTable } from '../components/suspects/SuspectTable';
import { LoadingSpinner } from '../components/common/LoadingSpinner';
import { EmptyState } from '../components/common/EmptyState';
import { formatNumber } from '../utils/formatters';

export function SuspectQueuePage({ onSelectSuspect, initialSearch = '' }) {
  const [data, setData] = useState({ items: [], total: 0, page: 1, size: 50 });
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);

  // Filters
  const [statusTab, setStatusTab] = useState('ALL'); // ALL, PENDING_REVIEW, REVIEWED
  const [gapType, setGapType] = useState('ALL'); // ALL, EMERGING, RECAPTURE
  const [priorityFilter, setPriorityFilter] = useState('ALL'); // ALL, HIGH, MEDIUM, LOW
  const [searchQuery, setSearchQuery] = useState(initialSearch);
  const [currentPage, setCurrentPage] = useState(1);

  const loadSuspects = async (page = 1) => {
    setIsLoading(true);
    setError(null);
    try {
      const params = {
        page,
        size: 50,
      };
      if (gapType !== 'ALL') params.type = gapType;
      if (priorityFilter !== 'ALL') params.ml_priority = priorityFilter;
      params.sort = 'ml_review_rank';
      params.order = 'asc';
      if (statusTab !== 'ALL') params.status = statusTab;

      const res = await suspectsApi.list(params);
      setData(res);
      setCurrentPage(page);
    } catch (err) {
      setError(err.message || 'Failed to load suspects queue.');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadSuspects(1);
  }, [statusTab, gapType, priorityFilter]);

  // Client-side search filtering across returned page items
  const filteredItems = useMemo(() => {
    if (!searchQuery.trim()) return data.items || [];
    const q = searchQuery.toLowerCase();
    return (data.items || []).filter((item) => {
      return (
        String(item.bene_id).toLowerCase().includes(q) ||
        String(item.hcc_v28).toLowerCase().includes(q) ||
        (item.hcc_description || '').toLowerCase().includes(q) ||
        (item.suspect_type || item.gap_type || '').toLowerCase().includes(q)
      );
    });
  }, [data.items, searchQuery]);

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <PageHeader
        eyebrow="Review & Triage Workspace"
        title="Suspect Triage Queue"
        description="Review and prioritize emerging and recapture HCC suspects generated by the 8-signal clinical inference engine."
        actions={
          <button
            onClick={() => loadSuspects(currentPage)}
            className="px-4 py-2 bg-surface-container text-on-surface font-manrope font-semibold text-xs rounded-xl hover:bg-surface-container-high transition-colors flex items-center gap-1.5"
          >
            <span className="material-symbols-outlined text-[18px]">refresh</span>
            <span>Refresh Queue</span>
          </button>
        }
      />

      {error && (
        <div className="p-4 bg-amber-50 border border-amber-200 rounded-xl text-amber-800 text-sm flex items-center gap-2 font-mono">
          <span className="material-symbols-outlined">warning</span>
          <span>{error}</span>
        </div>
      )}

      {/* Control Bar: Status Tabs, Search, and Dropdown Filters */}
      <div className="flex flex-col xl:flex-row items-center justify-between gap-4 bg-surface-container-lowest p-4 rounded-2xl shadow-sm border border-outline-variant/20">
        {/* Status Tabs */}
        <div className="flex items-center bg-surface-container-low p-1 rounded-xl w-full xl:w-auto">
          {[
            { id: 'ALL', label: 'All Suspects' },
            { id: 'PENDING_REVIEW', label: 'Pending Review' },
            { id: 'REVIEWED', label: 'Completed' },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setStatusTab(tab.id)}
              className={`px-4 py-2 rounded-lg font-mono text-xs font-semibold transition-all flex-1 xl:flex-none ${
                statusTab === tab.id
                  ? 'bg-primary text-on-primary shadow-xs'
                  : 'text-on-surface-variant hover:text-on-surface hover:bg-surface-container'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Search and Filters */}
        <div className="flex flex-wrap items-center gap-3 w-full xl:w-auto">
          {/* Search Box */}
          <div className="flex items-center bg-surface-container-low rounded-xl px-3.5 py-2 flex-1 xl:w-72 border border-outline-variant/20 focus-within:border-primary focus-within:bg-surface transition-all">
            <span className="material-symbols-outlined text-outline text-[18px] mr-2">search</span>
            <input
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search member, HCC, description..."
              className="bg-transparent w-full focus:outline-none text-xs font-mono text-on-surface placeholder:text-outline"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery('')}
                className="text-outline hover:text-on-surface text-xs font-mono ml-1"
              >
                ✕
              </button>
            )}
          </div>

          {/* Gap Type Filter */}
          <select
            value={gapType}
            onChange={(e) => setGapType(e.target.value)}
            className="bg-surface-container-low text-on-surface font-mono text-xs px-3 py-2 rounded-xl border border-outline-variant/20 outline-none"
          >
            <option value="ALL">All Types</option>
            <option value="EMERGING">Emerging Gap</option>
            <option value="RECAPTURE">Recapture Gap</option>
          </select>

          {/* Priority Filter */}
          <select
            value={priorityFilter}
            onChange={(e) => setPriorityFilter(e.target.value)}
            className="bg-surface-container-low text-on-surface font-mono text-xs px-3 py-2 rounded-xl border border-outline-variant/20 outline-none"
          >
            <option value="ALL">All Priorities</option>
            <option value="HIGH">High Priority</option>
            <option value="MEDIUM">Medium Priority</option>
            <option value="LOW">Low Priority</option>
          </select>
        </div>
      </div>

      {/* Main Table or Loading / Empty state */}
      {isLoading ? (
        <LoadingSpinner message="Fetching suspect candidates from Azure PostgreSQL..." />
      ) : filteredItems.length === 0 ? (
        <EmptyState
          title="No suspects found"
          message="No suspect candidates match the current filter or search criteria."
          icon="checklist"
          action={
            <button
              onClick={() => {
                setStatusTab('ALL');
                setGapType('ALL');
                setPriorityFilter('ALL');
                setSearchQuery('');
              }}
              className="px-4 py-2 bg-primary text-on-primary font-manrope font-bold text-xs rounded-xl shadow hover:bg-primary/90 transition-all"
            >
              Reset Filters
            </button>
          }
        />
      ) : (
        <>
          <div className="flex justify-between items-center px-1 text-xs font-mono text-on-surface-variant">
            <span>
              Showing {filteredItems.length} candidate(s) (Page {data.page} of {Math.ceil((data.total || 1) / data.size)})
            </span>
            <span>Total Candidates: {formatNumber(data.total)}</span>
          </div>

          <SuspectTable items={filteredItems} onSelectSuspect={onSelectSuspect} />

          {/* Pagination Controls */}
          <div className="flex justify-between items-center bg-surface-container-lowest p-4 rounded-2xl border border-outline-variant/20">
            <button
              disabled={currentPage <= 1 || isLoading}
              onClick={() => loadSuspects(currentPage - 1)}
              className="px-4 py-2 bg-surface-container text-on-surface font-mono text-xs rounded-xl hover:bg-surface-container-high disabled:opacity-40 transition-all flex items-center gap-1"
            >
              <span className="material-symbols-outlined text-[16px]">arrow_back</span>
              <span>Previous Page</span>
            </button>

            <span className="font-mono text-xs font-bold text-primary">
              Page {currentPage}
            </span>

            <button
              disabled={currentPage * data.size >= data.total || isLoading}
              onClick={() => loadSuspects(currentPage + 1)}
              className="px-4 py-2 bg-surface-container text-on-surface font-mono text-xs rounded-xl hover:bg-surface-container-high disabled:opacity-40 transition-all flex items-center gap-1"
            >
              <span>Next Page</span>
              <span className="material-symbols-outlined text-[16px]">arrow_forward</span>
            </button>
          </div>
        </>
      )}
    </div>
  );
}
